### ISSUE TITLE
Compatability issues with `sqlalchemy` versions >=1.2.0

### ISSUE THREAD

**Issue by jeffreythewang** [LocusEnergy/sqlalchemy-vertica-python#12]
Newer versions of `sqlalchemy` implement a `get_table_comment` method as described [here](http://docs.sqlalchemy.org/en/latest/core/reflection.html#sqlalchemy.engine.reflection.Inspector.get_table_comment). As a quick fix, we can support this method, but for a more long-term solution, should we consider not extending from `PGDialect`?

EDIT: mentioned wrong method (`get_table_comment` is missing, not `get_table_names`)

**Comment by lemeryfertitta** [comment]
From what I can tell, `get_table_names` is implemented [here](https://github.com/LocusEnergy/sqlalchemy-vertica-python/blob/master/sqla_vertica_python/vertica_python.py#L139). I also don't see how removing the `PGDialect` inheritance would relate to this issue. What exactly is the issue you are running into?

**Comment by lemeryfertitta** [comment]
I suspect you mentioned the wrong method in your issue description. Judging from the link, the intended method was `get_table_comment`. From a quick glance at the Vertica docs, it looks like `V_CATALOG.COMMENTS` stores this information. I'd be happy to accept a PR and package up a new release if you want to implement this functionality.

I still don't see the relation to `PGDialect`

**Comment by jeffreythewang** [comment]
Yes my bad, I mentioned the wrong method (edited to reflect that).

My suggestion to not extend from `PGDialect` is that any time a new method is added there, we'll have to add it here, and Vertica may not necessarily be similar enough to PostgreSQL to warrant extending from it.

**Comment by lemeryfertitta** [comment]
Fair point. I'm hesitant to just remove it, because the `PGDialect` class is fairly substantial and I can't immediately determine if any existing functionality would be broken. If you want to make a separate PR that removes the dependency and implements any missing functionality, I'd be happy to review that as well. I'd recommend keeping the fix for this issue separate for a faster fix.

**Comment by lemeryfertitta** [comment]
Released in 0.2.2
