### ISSUE TITLE
(VerticaDialect) native Decimal support not enabled

### ISSUE THREAD

**Issue by pachewise** [LocusEnergy/sqlalchemy-vertica-python#17]
Getting this when retrieving Decimal/Numeric objects from Vertica:
```
SAWarning: Dialect vertica+vertica_python does *not* support Decimal objects natively, and SQLAlchemy must convert from floating point - rounding errors and other issues may occur. Please consider storing Decimal numbers as strings or integers on this platform for lossless storage.
  'storage.' % (dialect.name, dialect.driver))
```
This is causing issues in our repo because we use `Numeric(19, 0)`, which incurs precision loss when converted to float. 
Since Vertica supports Decimal/Numeric, this is simply a configuration issue (we need to set `supports_native_decimal = True`).

**Comment by lemeryfertitta** [comment]
Thanks. Released in `0.3.1.` along with your unicode fixes
