### ISSUE TITLE
Issue with reflexivity

### ISSUE THREAD

**Issue by edurand** [LocusEnergy/sqlalchemy-vertica-python#2]
I'm having issues with the following: 

```
In [12]: tab = Table('exac', meta, autoload=True, autoload_with=eng)
('in get columns', 'exac')
ProgrammingError: (vertica_python.errors.MissingSchema) Severity: ERROR, Message: Schema "pg_catalog" does not exist, Sqlstate: 3F000, Routine: RangeVarGetObjid, File: /scratch_a/release/svrtar17878/vbuild/vertica/Catalog/Namespace.cpp, Line: 288
```

I saw there was a PR on a very similar issue that supposedly fixed the problem. Any hint? 
I install psycopg2 and sqlalchemy-vertica-python 0.1.3. 

Thanks.

**Comment by lemeryfertitta** [comment]
This should be fixed by the PR which correctly points get_columns to vg_catalog. This will be included in the next release
