### ISSUE TITLE
b'ERROR', Message: b'Type "TEXT" does not exist' when using sqlalchemy-vertica-python with pandas

### ISSUE THREAD

**Issue by bmoscon** [LocusEnergy/sqlalchemy-vertica-python#20]
using pandas' to_sql method with sqlalchemy-vertica-python results in this error:

```
conn = sa.create_engine('vertica+vertica_python://connection-string')
df.to_sql(table, conn, schema=schema)
```

if `df` has any strings in it, the above error will ensue.

**Comment by lemeryfertitta** [comment]
@bmoscon thanks for the error report. I just released a patch `0.3.2` to alias `TEXT` to `VARCHAR`. I don't have a setup to easily test your issue, but I believe that should fix it. Feel free to reopen this issue with additional information if it is not resolved.
