### ISSUE TITLE
Want to ignore any typeargs or typekwargs for DATE, DATETIME, TIMESTAMP, and TZ equivalents

### ISSUE THREAD

**Issue by robin900** [LocusEnergy/sqlalchemy-vertica-python#21]
Some Vertica databases can have tables defined whose columns have type arguments to DATE or  TIMESTAMP. These are bogus but Vertica accepts them. Then they're reported to the SQLA inspector and are passed as `typeargs` to the sqltypes type object, which causes an exception.

The solution is to instantiate the type objects in `ischema_names`, just as the timezone-aware types are; then `_get_column_info` will no longer attempt to call type objects that aren't expecting any typeargs.

**Comment by lemeryfertitta** [comment]
Released in 0.3.3
