### ISSUE TITLE
Data types in Vertica with spaces in type name do not reflect correctly

### ISSUE THREAD

**Issue by robin900** [LocusEnergy/sqlalchemy-vertica-python#27]
Types like `LONG VARCHAR` and `LONG VARBINARY` are not reflected properly; instead the regular expression at line 256 matches just `LONG` and erroneously produces a `sqlalchemy.INTEGER` type for the column.

A PR with tested fix is forthcoming; I request an urgent merge and release.

**Comment by lemeryfertitta** [comment]
Released in `0.4.1`, I don't think I'll always be able to make release within an hour, but glad it worked out this time 😄
