### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by pachewise** [LocusEnergy/sqlalchemy-vertica-python#35]
Wondering if there are any plans to officially state which versions this supports? I don't see any incompatibilities with py3, but right now there is no PyPI or GitHub documentation pointing at which versions this supports.

**Comment by lemeryfertitta** [comment]
Hi @pachewise, a couple notes:

- In my experience, we used this library with python3 frequently and had no issues. I also took a quick glance and agree that there are no glaring python3 incompatibilities. That said, I have never been an extensive user of the reflection features and thus have not run all of the code paths in this library with python3.

- I have changed companies and, as far as I know, there are no other maintainers remaining with Locus Energy. I no longer feel that I am in a position to be able to contribute to and maintain this library, so I would recommend potentially forking and creating a new PyPI entry or claiming this one if changes are needed. Ideally, the Vertica folks would take this role, but I believe the last conversation on the vertica-python issue page concluded with a lack of resources on their part to properly support this library.
